/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RocketsImport } from './routes/rockets'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RocketsRoute = RocketsImport.update({
  id: '/rockets',
  path: '/rockets',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/rockets': {
      id: '/rockets'
      path: '/rockets'
      fullPath: '/rockets'
      preLoaderRoute: typeof RocketsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rockets': typeof RocketsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rockets': typeof RocketsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/rockets': typeof RocketsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rockets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rockets'
  id: '__root__' | '/' | '/rockets'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RocketsRoute: typeof RocketsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RocketsRoute: RocketsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/rockets"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/rockets": {
      "filePath": "rockets.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
